export const ADD_MINING_TIME_BY_BLOCKS_ACTION = 'ADD_MINING_TIME_BY_BLOCKS';

export const ADD_MINING_TIME_BY_TIME_ACTION = 'ADD_MINING_TIME_BY_TIME';

export const API_ERROR_ACTION = 'API_ERROR';

export const ADD_MINING_TIME_BY_TIME_FORM_ERROR_ACTION = 'ADD_MINING_TIME_BY_TIME_FORM_ERROR';

export const ADD_MINING_TIME_BY_BLOCKS_FORM_ERROR_ACTION = 'ADD_MINING_TIME_BY_BLOCKS_FORM_ERROR';
